-- 수학초미녀의 비밀 연구실: 학생 결과 저장 테이블
-- Supabase Dashboard > SQL Editor에서 이 파일 전체를 한 번 실행하세요.

create table if not exists public.escape_results (
  id bigint generated by default as identity primary key,
  class_name text not null,
  student_number text not null,
  student_name text not null,
  run_id text unique,
  elapsed_seconds integer not null check (elapsed_seconds >= 0),
  remaining_seconds integer not null check (remaining_seconds >= 0),
  attempts_json jsonb not null default '{}'::jsonb,
  score integer not null default 1000 check (score >= 0),
  time_cost integer not null default 0 check (time_cost >= 0),
  wrong_count integer not null default 0 check (wrong_count >= 0),
  wrong_cost integer not null default 0 check (wrong_cost >= 0),
  hint_cost integer not null default 0 check (hint_cost >= 0),
  hints_json jsonb not null default '{}'::jsonb,
  bonus_score integer not null default 0 check (bonus_score >= 0),
  bonus_json jsonb not null default '{}'::jsonb,
  final_score integer not null default 1000 check (final_score >= 0),
  rank text not null default 'D — 탈출 성공!',
  reflection text not null default '',
  rating integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  message_restored boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists escape_results_class_idx
  on public.escape_results (class_name, student_number);

-- 학생의 브라우저가 데이터베이스를 직접 읽거나 쓰지 못하게 합니다.
-- 결과 저장은 사이트의 서버 API와 서버 비밀키를 통해서만 이루어집니다.
alter table public.escape_results enable row level security;
revoke all on table public.escape_results from anon, authenticated;

comment on table public.escape_results is
  '수학초미녀의 비밀 연구실 학생별 방탈출 및 보너스 결과';
